version: '3'

services:

# NODE JS  
  node:
    build: .
    image: samu_node
    container_name: node
    working_dir: /usr/src/app
    env_file:
      - config/.env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "80:80"
    command: bash -c "npm run start"
    networks:
      - samutips
    depends_on:
      - db

# POSTGRES
  db:
    image: postgres:12
    restart: always
    container_name: samu_pg
    env_file:
      - config/.env
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/10-init.sql
    networks:
      - samutips
    
networks:
    samutips:


